$('.productReviewsSlider').slick({
    infinite: true,
    slidesToShow: 1,
    slidesToScroll: 1,
    prevArrow: (".ReviewsslidersPrev"),
    nextArrow: (".ReviewsslidersNext"),
    dots: true,
    appendDots: $('.productReviewsDots'),
    draggable: true,
    dots: true,
    fade: true,
    speed: 500,
    infinite: true,
    cssEase: 'ease-in-out',
    touchThreshold: 100,
})